version: 2

project_name: pipeboard

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pipeboard
    main: .
    binary: pipeboard
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - SECURITY.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${signature}.pem"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: blackwell-systems
    name: pipeboard
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: pipeboard
    repository:
      owner: blackwell-systems
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/blackwell-systems/pipeboard"
    description: "Tiny cross-platform clipboard CLI with SSH + S3 sync"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/pipeboard", "version"
    install: |
      bin.install "pipeboard"

nfpms:
  - id: packages
    package_name: pipeboard
    vendor: Blackwell Systems
    homepage: https://github.com/blackwell-systems/pipeboard
    maintainer: Blackwell Systems <blackwellsystems@protonmail.com>
    description: Cross-platform clipboard CLI with SSH + S3 sync
    license: MIT
    formats:
      - deb
      - rpm
    recommends:
      - xclip
    bindir: /usr/bin
    contents:
      - src: man/man1/pipeboard.1
        dst: /usr/share/man/man1/pipeboard.1
      - src: LICENSE
        dst: /usr/share/doc/pipeboard/LICENSE
