version: 2

project_name: pipeboard

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pipeboard
    main: .
    binary: pipeboard
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - SECURITY.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: blackwell-systems
    name: pipeboard
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: pipeboard
    repository:
      owner: blackwell-systems
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/blackwell-systems/pipeboard"
    description: "Tiny cross-platform clipboard CLI with SSH + S3 sync"
    license: "MIT"
    skip_upload: true  # Disabled until HOMEBREW_TAP_TOKEN is fixed (401 error)
    test: |
      system "#{bin}/pipeboard", "version"
    install: |
      bin.install "pipeboard"
