//go:build ignore

package main

import (
	"encoding/base64"
	"fmt"
	"os"
)

func main() {
	testCases := []struct {
		name       string
		plaintext  string
		passphrase string
	}{
		{
			name:       "simple-text",
			plaintext:  "Hello, Pipeboard!",
			passphrase: "test-password-123",
		},
		{
			name:       "empty-data",
			plaintext:  "",
			passphrase: "test-password",
		},
		{
			name:       "unicode-text",
			plaintext:  "Hello 🚀 World\nNew line\tTab",
			passphrase: "test-password",
		},
		{
			name:       "special-chars-password",
			plaintext:  "test data",
			passphrase: "pä$$wörd-with-ümläuts",
		},
	}

	fmt.Println("# Test Vectors for Android Compatibility Testing")
	fmt.Println("# Generated by pipeboard CLI crypto implementation")
	fmt.Println()

	for _, tc := range testCases {
		encrypted, err := encrypt([]byte(tc.plaintext), tc.passphrase)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error encrypting %s: %v\n", tc.name, err)
			continue
		}

		fmt.Printf("## Test: %s\n", tc.name)
		fmt.Printf("Plaintext: %q\n", tc.plaintext)
		fmt.Printf("Passphrase: %q\n", tc.passphrase)
		fmt.Printf("Encrypted (base64): %s\n", base64.StdEncoding.EncodeToString(encrypted))
		fmt.Printf("Encrypted (hex): %x\n", encrypted)
		fmt.Println()

		// Write binary file for Android test resources
		filename := fmt.Sprintf("test-vector-%s.bin", tc.name)
		err = os.WriteFile(filename, encrypted, 0644)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", filename, err)
		} else {
			fmt.Printf("Written to: %s\n\n", filename)
		}
	}
}
